### ISSUE TITLE
Getting an empty href

### ISSUE THREAD

**Issue by wfendler** [jlmessenger/Statamic-SASS#1]
I've got this in my layout file: `<link rel="stylesheet" href="{{ sass src="scss/wfendler.scss" }}">` and the location of the sass file is here: `/_themes/wfendler/scss/wfendler.scss` but I'm getting an empty `href` in the output. Also, the location of the add-on is here: `/_config/add-ons/sass/` 

Am I missing something?

**Comment by jlmessenger** [comment]
Try adding the `error="die"` option. It will make the plugin kill the script immediately if there are any errors and print them onto the page. There is also an option called `dev="true"` that enables this and other useful options during development.

`<link rel="stylesheet" href="{{ sass src='scss/wfendler.scss' dev='true' }}">`

Just remember to turn off development mode when you go-live.
Enjoy!
